name: db_context_lib
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: kernel <email@example.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  logging: 0.11.3+2
  resource_pool:
    git: https://github.com/radzish/resource_pool.git

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.9.4
